//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoList.Core.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Msg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Msg() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TodoList.Core.Application.Resources.Msg", typeof(Msg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a COD0003.
        /// </summary>
        public static string DADOS_DO_X0_NAO_ENCONTRADO_COD {
            get {
                return ResourceManager.GetString("DADOS_DO_X0_NAO_ENCONTRADO_COD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dados do {0} não encontrado..
        /// </summary>
        public static string DADOS_DO_X0_NAO_ENCONTRADO_TXT {
            get {
                return ResourceManager.GetString("DADOS_DO_X0_NAO_ENCONTRADO_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a COD0002.
        /// </summary>
        public static string DATA_BASE_SERVER_ERROR_COD {
            get {
                return ResourceManager.GetString("DATA_BASE_SERVER_ERROR_COD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Database server error..
        /// </summary>
        public static string DATA_BASE_SERVER_ERROR_TXT {
            get {
                return ResourceManager.GetString("DATA_BASE_SERVER_ERROR_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a COD0003.
        /// </summary>
        public static string FALHA_AO_REMOVER_X0_COD {
            get {
                return ResourceManager.GetString("FALHA_AO_REMOVER_X0_COD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha ao remover o {0}..
        /// </summary>
        public static string FALHA_AO_REMOVER_X0_TXT {
            get {
                return ResourceManager.GetString("FALHA_AO_REMOVER_X0_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a COD0005.
        /// </summary>
        public static string IDENTIFICADOR_X0_INVÁLIDO_COD {
            get {
                return ResourceManager.GetString("IDENTIFICADOR_X0_INVÁLIDO_COD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Indentificador {0} inválido..
        /// </summary>
        public static string IDENTIFICADOR_X0_INVÁLIDO_TXT {
            get {
                return ResourceManager.GetString("IDENTIFICADOR_X0_INVÁLIDO_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a COD0004.
        /// </summary>
        public static string INTERNAL_SERVER_ERROR_COD {
            get {
                return ResourceManager.GetString("INTERNAL_SERVER_ERROR_COD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Internal server error..
        /// </summary>
        public static string INTERNAL_SERVER_ERROR_TXT {
            get {
                return ResourceManager.GetString("INTERNAL_SERVER_ERROR_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a COD0001.
        /// </summary>
        public static string X0_E_OBRIGATORIO_COD {
            get {
                return ResourceManager.GetString("X0_E_OBRIGATORIO_COD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} é obrigatório..
        /// </summary>
        public static string X0_E_OBRIGATORIO_TXT {
            get {
                return ResourceManager.GetString("X0_E_OBRIGATORIO_TXT", resourceCulture);
            }
        }
    }
}
